### ISSUE TITLE
[Sponge API 7.0] Error on server start

### ISSUE THREAD

**Issue by Krosta8** [rojo8399/PlaceholderAPI#47] opened 2017-12-04 19:03 UTC
SpongeAPI version: 
7.0.0
PlaceholderAPI version: 
4.3
Plugins installed: 
PlaceHolderAPI, Command Utils, Nucleus, Badge, GriefPrevention, VirtualChest, UltimateChat, TotalEconomy, ProjectCore, ProjectPortals, LuckPerms
Error log [if any]: (please use PasteBin or similar services to shorten error logs)
https://pastebin.com/PV86Y5wv
Description: 
After update to latest version of SpongeForge 1.12.2 (build 2757) PlaceHolderAPI is not working.
Steps to reproduce:
Use SpongeForge 1.12.2 API 7.0.0, build 2757
Start server and error appears.

**Comment by Wundero** [comment] 2017-12-05 21:29
Duplicate of #43.

**Closed as completed by Wundero** 2017-12-05 21:29 UTC
