### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by ziceptor** [rojo8399/PlaceholderAPI#46] opened 2017-12-01 23:07 UTC
https://gist.github.com/ziceptor/65a3fb9f6351257f0d696ae77504071c

forge-1.12.2-14.23.0.2529-universal.jar
spongeforge-1.12.2-2529-7.0.0-BETA-2748.jar
PlaceholderAPI-4.3.jar

**Comment by Wundero** [comment] 2017-12-01 23:15
Duplicate of #43.

**Closed as completed by Wundero** 2017-12-01 23:15 UTC
