### ISSUE TITLE
[Sponge API 5.2.0]VirtualChest and Total Economy/EconomyLite

### ISSUE THREAD

**Issue by Krosta8** [rojo8399/PlaceholderAPI#37] opened 2017-10-25 19:01 UTC
### Please provide these fields before submitting an issue.

SpongeAPI version: 5.20

PlaceholderAPI version: 4.1

Plugins installed: 
- ActionMessage
- BungeeTabListPlus
- CatClearLag
- CommandUtils
- EasyScoreboards
- GriefPrevention
- LuckPerms
- Nucleus
- PixelAutoMessages
- PlaceHolderAPI
- ProjectCore
- ProjectPortals
- Total Economy
- Ultimate Chat
- VirtualChest
- WorldEdit

Description: 
Hello, first of all I would like to say, that I tried it just with installed VirtualChest, PlaceHolderAPI and Total Economy and the result was the same.

I want to use your place holder %economy_balance_[currency]%, because in Total Economy I have two currencies (Tokens and Kredits). In VirtualChest I want to have both currencies for buying items and it is using your place holders for this. I tried to use %economy_balance_kredits% and %economy_balance_[kredits]%. Neither of it works. Everytime it was using the default currency (tokens). 
I contacted author of Total Economy, but he said, that he doesn't know how both of this plugins works.

Is it a problem on his side or this side? 
I just need to be able to reference for the currencies.

PS: I tried to do the same with EconomyLite and the result was same and author said the same 😄 
PPS: I tried to do the same on Sponge API 7.0.0 (but in scoreboard instead of VirtualChest) and result was same.

Steps to reproduce:
Just tried to use the placeholder anywhere (scoreboard, virtualchest, etc.) with Total Economy. It will always show the default currency.

Thank you a lot,
Krosta8

**Comment by Wundero** [comment] 2017-10-26 02:46
Thanks for the report, I will try to have this fixed in the next version of PlaceholderAPI.

**Comment by Wundero** [comment] 2017-10-27 19:54
So this seems strange to me, but I cannot seem to replicate this in the latest version (perhaps I already fixed it unintentionally?). My test case has two currencies using TotalEconomy: "dollar" and "token", which have default balances of 100 and 10, respectively. I used `/papi p <player name> %economy_balance%` and `/papi p <player name> %economy_balance_token%`, and they returned the correct default balances. I am fixing things in the placeholder as well that I have noticed, since when I wrote it I had no way to test it. I will be pushing the update soon.

**Comment by Krosta8** [comment] 2017-10-27 20:05
I tried to use it too, exactly like you and the result was for both commands the same. Still can see just the default currency value.
I hope for the update very soon and I can test it for you, if it is really working.

Again, thank you so much 🙂

**Comment by Krosta8** [comment] 2017-11-01 23:02
I don't want to look like impatient, but could you please release the version just like it is right at this moment? I really need it and I don't have experience how to build it on my own from the code. 
I need it for my both server on API 7 and API 5.2.0.

Sorry for me being impatient.

**Closed as completed** 2017-11-05 11:19 UTC
Labels: type: bug, status: confirmed

**Comment by Wundero** [comment] 2017-11-06 20:36
Is this confirmed to be fixed? I haven't run tests on anything other that SpongeAPI 6, so I have no verification, as well as not having run many tests.

**Comment by Krosta8** [comment] 2017-11-06 20:41
Yes, I tried it and everything seems to work properly on API 7.0.0 and API 5.2.0
Thank you very much! 🙂
